//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegistration
    {
        public int RegisterID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string EmailID { get; set; }
        public string PhoneNumber { get; set; }
        public string AddressOne { get; set; }
        public string AddressTwo { get; set; }
        public Nullable<int> RoleID { get; set; }
    }
}
